language: java
jdk:
  - oraclejdk8
env:
global:
- secure: "SRgXCRvCDLAc/HmKUQNc52uiHQAEicXJ+Sel8p5EPVjU32qhbz9T0AwTFIqx6hUkF758bTl0A76mNOHSk8WysmawjPwyN20lH5MrQZPVBN5rrXWbc8LERfRgp+BbXx8IhPiX+466+NLCDbE6Npvpo4bgb4sAfRzONj14FWUkseDt4rEoJ9NyD11o1MZAUMAQ+x26JAUfZPcmhas88JfSgnHsY+NI5UscoX2fgblah1+mcIKryjK5ITlsflZB9hhbDks39nbdUkctZoshb7NDxUwTAohi4GAGbqywOHIggxrO7J5TqzSB2U2jQ6gVM0HULPutcPPFtMCy5R04MIAR2UZRoGor3A6FN6idCjfsh9SCm3AvcwO/OtP4VMnj4l5nr4Ua4BhBeati/rQt4Fwly9rXeDyeBsFehz3n7w08PbWFsQs2WMlhqST4MMlTSIDTJQjpYrM+AKR4QvTV0GjAwbZCW+uNfa1f1R6FhLVIvkR0qlzs6OHr9ksi2vkqYtHo00KfwxBZ7uuCiS2KzjGfyNiLw3N2twp7/T9990aJSkPlV8xIydb3c+8ExNSZ+/yyfghvZfLw8RfnLlGVZixN2K7bqbsXO/WKMhg1stV9GfXcP/uQmcNJBVDrmqMwyCzJaxS8QLIxEXlxn4cuX8+pRQpDIr4ImurKVhXjBf2tOK4="
before_install:
- export TERM=dumb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: ./gradlew integTest check Javadoc --info --stacktrace
deploy:
  provider: releases
  api_key:
    secure: WmnSkwn+vrPgWoPWOIb1dN48lBWcvlOefbkcDod4nUqMY7XHnyPDAGzrQWDSB9HRy5F9+bV3hqV1foZnVwePTH7XRD7R0cUETLa3KPTiiFIbvzCsZMnU9Tkf1/mu0xqOPTAXZP7eLnlwS7QO88UN4kfnH0oxBUOLvS8JiBcNBdp/pP2ORulOyxJbeF6PRKvG+mLpnu+zpGQ70XNu+yivpKlN3OPOUqJ7HFm8yufHJy6zHStaeLBx9vNAIlIMp5CBJqNMaKO3QvFri1BdYRw2d5mRz0BXRruNBRTAin2OWHhv5wM5TTAv+O1UFVKTuJZKk4MiPC2UeVFiu1I3zaTfP5cPQ7B6crz+BgbCpBBWWQrLgWDarVo1nmmWGIGPfsxzVM7C/x1NTDzpjvFV4DFwC5CfgnTwZLjock1NK0THMUHuzYTv4rG+0fMLs2z36l9/pdSlz+JUZmXHuoa7oVQNQ3bei6sYCv+P5dgbXQcscB5g+PsUKoCNx5s3swvR5cRJZ+8FHvyD9EE6uzmHirlwEnMMfKOTIY4yzk0oOoHXzZx9H1veOOlpRjeYKba5E9JkcTFNog2EK+PHwljOI8BoTb5Nt56aWDnmJnJQKfFItPle1+YwSqOS8hDNKUyq+NEDdj+yUEHkYg1IlMx+22Pe4GFK/YB2+BuNykknZ0/AgDk=
  file: "build/distributions/TicTacToe.zip"
  skip_cleanup: true
  on:
    repo: HEX2016/TicTacToe
    branch: JarFileCreation
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .utility/push-javadoc-to-gh-pages.sh