language: java
jdk:
  - oraclejdk8
  env:
  global:
    secure: "SRgXCRvCDLAc/HmKUQNc52uiHQAEicXJ+Sel8p5EPVjU32qhbz9T0AwTFIqx6hUkF758bTl0A76mNOHSk8WysmawjPwyN20lH5MrQZPVBN5rrXWbc8LERfRgp+BbXx8IhPiX+466+NLCDbE6Npvpo4bgb4sAfRzONj14FWUkseDt4rEoJ9NyD11o1MZAUMAQ+x26JAUfZPcmhas88JfSgnHsY+NI5UscoX2fgblah1+mcIKryjK5ITlsflZB9hhbDks39nbdUkctZoshb7NDxUwTAohi4GAGbqywOHIggxrO7J5TqzSB2U2jQ6gVM0HULPutcPPFtMCy5R04MIAR2UZRoGor3A6FN6idCjfsh9SCm3AvcwO/OtP4VMnj4l5nr4Ua4BhBeati/rQt4Fwly9rXeDyeBsFehz3n7w08PbWFsQs2WMlhqST4MMlTSIDTJQjpYrM+AKR4QvTV0GjAwbZCW+uNfa1f1R6FhLVIvkR0qlzs6OHr9ksi2vkqYtHo00KfwxBZ7uuCiS2KzjGfyNiLw3N2twp7/T9990aJSkPlV8xIydb3c+8ExNSZ+/yyfghvZfLw8RfnLlGVZixN2K7bqbsXO/WKMhg1stV9GfXcP/uQmcNJBVDrmqMwyCzJaxS8QLIxEXlxn4cuX8+pRQpDIr4ImurKVhXjBf2tOK4="
 before_install:
- export TERM=dumb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: ./gradlew integTest check Javadoc --info --stacktrace
after_success:
- .utility/initiate-publish.sh
- .utility/push-javadoc-to-gh-pages.sh