/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'egill_000' at '10/19/16 1:59 PM' with Gradle 3.1
 *
 * @author egill_000, @date 10/19/16 1:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
